image:
  pixel_scale: 0.2
  size_x: 32
  size_y: 32
  n_objects: 1
  noise:
    type: Gaussian
    sigma: 0.01

psf:
  type: Gaussian
  sigma: 0.1

gal:
  type: Exponential
  flux:
    type: LogNormal
    mean: 100.0
    sigma: 0.1
  half_light_radius:
    type: Uniform
    min: 0.3
    max: 0.8
  shear:
    type: G1G2
    g1: 
      type: Normal
      mean: 0.05
      sigma: 0.02
    g2: 
      type: Normal
      mean: -0.05
      sigma: 0.02

inference:
  warmup: 100
  samples: 100
  chains: 1
